const router=require('express').Router();
const main=require('../model/main');
router.get('/',main.main);
router.get('/search',main.search);
router.get('/proDetail',main.proDetail);
router.get('/test',main.test);
router.get('/imedi',main.orderForm);
router.get('/myPage',main.myPage);
router.get('/orderInfo',main.orderInfo);
router.get('/basket',main.basket);
router.get('/orderFinish',main.orderFinish);
module.exports=router;