const router=require('express').Router();
const main=require('../model/main');
router.get('/',main.main);
router.get('/glove',main.glove);
router.get('/sandbag',main.sandbag);
router.get('/headgear',main.headgear);
router.get('/etc',main.etc);
router.get('/prodetail',main.proDetail);
router.get('/test',main.test);
module.exports=router;